#!/usr/bin/env bash
# Installs Tienda POS on a Linux laptop (tested on Ubuntu; recommended: Linux Mint 22 XFCE or Lubuntu).
# Creates the virtual environment, .env, database, owner account and, unless --no-service is given,
# a systemd service that starts at boot plus a daily verified backup timer.
# Every step is idempotent: run it again after pulling a new version.
#
#   bash scripts/linux/install.sh [--printer-host 192.168.1.50] [--backup-dir /media/usb/backups]
#                                 [--port 8008] [--no-service] [--skip-superuser] [--seed-catalog]
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"
PORT=8008; PRINTER_HOST=''; BACKUP_DIR=''; NO_SERVICE=0; SKIP_SUPERUSER=0; SEED=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --printer-host) PRINTER_HOST="$2"; shift 2 ;;
    --backup-dir) BACKUP_DIR="$2"; shift 2 ;;
    --port) PORT="$2"; shift 2 ;;
    --no-service) NO_SERVICE=1; shift ;;
    --skip-superuser) SKIP_SUPERUSER=1; shift ;;
    --seed-catalog) SEED=1; shift ;;
    *) echo "Unknown option: $1"; exit 2 ;;
  esac
done
step() { printf '\n\033[32m==> %s\033[0m\n' "$1"; }

step 'Checking Python (3.12 or newer)'
if ! python3 -c 'import sys; sys.exit(sys.version_info < (3, 12))' 2>/dev/null; then
  echo 'Python 3.12 or newer is required. On Ubuntu/Mint: sudo apt install python3'
  exit 1
fi
# Debian/Ubuntu ship venv without ensurepip unless python3-venv is installed.
if [[ ! -x .venv/bin/python ]] && ! python3 -c 'import ensurepip' 2>/dev/null; then
  echo "The venv module is incomplete. Install it with: sudo apt install python$(python3 -c 'import sys; print(*sys.version_info[:2], sep=".")')-venv"
  exit 1
fi
python3 --version

step 'Creating the virtual environment and installing dependencies'
[[ -x .venv/bin/python ]] || python3 -m venv .venv
PY="$ROOT/.venv/bin/python"
"$PY" -m pip install --disable-pip-version-check --quiet --upgrade pip
"$PY" -m pip install --disable-pip-version-check --quiet -r requirements.txt

step 'Writing .env (kept outside Git)'
LAN_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
if [[ ! -f .env ]]; then
  SECRET="$("$PY" -c 'import secrets; print(secrets.token_urlsafe(50))')"
  HOSTS="127.0.0.1,localhost${LAN_IP:+,$LAN_IP}"
  {
    echo '# Generated by scripts/linux/install.sh. See .env.example for every option.'
    echo "POS_SECRET_KEY=$SECRET"
    echo 'POS_DEBUG=0'
    echo "POS_ALLOWED_HOSTS=$HOSTS"
    echo "POS_PORT=$PORT"
    echo "POS_PRINTER_HOST=$PRINTER_HOST"
    echo 'POS_PRINTER_PORT=9100'
    echo 'POS_PRINTER_COLUMNS=42'
    echo 'POS_PRINTER_ACCENTS=1'
    [[ -n "$BACKUP_DIR" ]] && echo "POS_BACKUP_DIR=$BACKUP_DIR"
  } > .env
  chmod 600 .env
  echo "Created .env (LAN address: ${LAN_IP:-unknown})."
else
  echo '.env already exists; it was not changed.'
fi

step 'Preparing the database and static files'
"$PY" manage.py migrate --noinput --verbosity 0
"$PY" manage.py collectstatic --noinput --verbosity 0
"$PY" manage.py check

if [[ $SKIP_SUPERUSER -eq 0 ]]; then
  HAS_OWNER="$("$PY" manage.py shell -c 'from django.contrib.auth import get_user_model; print(get_user_model().objects.filter(is_superuser=True).exists())')"
  if [[ "$HAS_OWNER" != 'True' ]]; then
    step 'Create the OWNER account (full access: catalog, receiving, reports, returns)'
    "$PY" manage.py createsuperuser
  fi
fi
if [[ $SEED -eq 1 ]]; then
  step 'Loading the reference grocery catalog (approximate prices, no stock)'
  "$PY" manage.py seed_catalog
fi

if [[ $NO_SERVICE -eq 0 ]]; then
  step 'Installing the systemd service and the daily backup timer (asks for your password)'
  sudo tee /etc/systemd/system/tienda-pos.service > /dev/null <<UNIT
[Unit]
Description=Tienda POS (waitress)
After=network-online.target
Wants=network-online.target

[Service]
User=$USER
WorkingDirectory=$ROOT
ExecStartPre=$PY manage.py migrate --noinput
ExecStart=$PY -m waitress --listen=0.0.0.0:$PORT --threads=6 config.wsgi:application
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT
  sudo tee /etc/systemd/system/tienda-pos-backup.service > /dev/null <<UNIT
[Unit]
Description=Tienda POS verified database backup

[Service]
Type=oneshot
User=$USER
WorkingDirectory=$ROOT
ExecStart=/usr/bin/env bash $ROOT/scripts/linux/backup.sh
UNIT
  sudo tee /etc/systemd/system/tienda-pos-backup.timer > /dev/null <<UNIT
[Unit]
Description=Daily Tienda POS backup at 22:00

[Timer]
OnCalendar=*-*-* 22:00:00
Persistent=true

[Install]
WantedBy=timers.target
UNIT
  sudo systemctl daemon-reload
  sudo systemctl enable --now tienda-pos.service tienda-pos-backup.timer
  if command -v ufw > /dev/null && sudo ufw status | grep -q 'Status: active'; then
    sudo ufw allow from 192.168.0.0/16 to any port "$PORT" proto tcp
  fi

  step 'Creating the desktop launcher'
  BROWSER="$(command -v chromium || command -v chromium-browser || command -v google-chrome || true)"
  EXEC="xdg-open http://127.0.0.1:$PORT/"
  [[ -n "$BROWSER" ]] && EXEC="$BROWSER --app=http://127.0.0.1:$PORT/"
  mkdir -p "$HOME/.local/share/applications"
  cat > "$HOME/.local/share/applications/tienda-pos.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=Tienda POS
Comment=Abrir la caja
Exec=$EXEC
Icon=applications-office
Terminal=false
DESKTOP
  [[ -d "$HOME/Desktop" ]] && cp "$HOME/.local/share/applications/tienda-pos.desktop" "$HOME/Desktop/" && chmod +x "$HOME/Desktop/tienda-pos.desktop"
  [[ -d "$HOME/Escritorio" ]] && cp "$HOME/.local/share/applications/tienda-pos.desktop" "$HOME/Escritorio/" && chmod +x "$HOME/Escritorio/tienda-pos.desktop"
fi

step 'Done'
echo "Open http://127.0.0.1:$PORT/ on this computer."
[[ -n "$LAN_IP" ]] && echo "Phones on the same Wi-Fi: http://$LAN_IP:$PORT/  (fix this IP in the router with a DHCP reservation)"
[[ $NO_SERVICE -eq 1 ]] && echo "Start it manually with: bash scripts/linux/start.sh"
exit 0
