# Generated by Django 5.2.17 on 2026-09-30 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('unit', models.CharField(choices=[('piece', 'pieza'), ('kg', 'kg (a granel)'), ('liter', 'litro'), ('pack', 'paquete')], default='piece', max_length=24)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('photo', models.FileField(blank=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tienda', max_length=60)),
                ('header', models.TextField(blank=True, help_text='Dirección, teléfono u horario; una idea por renglón.')),
                ('footer', models.TextField(blank=True, default='¡Gracias por su compra!', help_text='Mensaje al final del ticket; una idea por renglón.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('supplier', models.CharField(max_length=120)),
                ('document', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_changes', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('deactivate', 'Baja'), ('reactivate', 'Reactivación')], max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('payment', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('credit', 'Fiado')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='store.sale')),
            ],
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('credit', 'Fiado')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns_authorized', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='store.sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('restock', models.BooleanField(default=True)),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='store.saleline')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='store.salereturn')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.CharField(default='MAIN', max_length=30)),
                ('opening_float', models.DecimalField(decimal_places=2, max_digits=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_count', models.JSONField(blank=True, default=dict)),
                ('closing_count', models.JSONField(blank=True, default=dict)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salereturn',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='store.shift'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='store.shift'),
        ),
        migrations.CreateModel(
            name='RemovedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('removed', 'Quitado'), ('reduced', 'Cantidad reducida'), ('cleared', 'Venta vaciada')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='removed_lines', to='store.shift')),
            ],
        ),
        migrations.CreateModel(
            name='PrintAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(choices=[('sale', 'Ticket de venta'), ('shift_open', 'Apertura de turno'), ('shift_close', 'Corte de turno'), ('test', 'Prueba')], default='sale', max_length=20)),
                ('result', models.CharField(choices=[('ok', 'Correcto'), ('failed', 'Falló'), ('manual', 'Navegador')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_attempts', to='store.sale')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_attempts', to='store.shift')),
            ],
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment', models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='store.customer')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments', to='store.shift')),
            ],
        ),
        migrations.CreateModel(
            name='CashOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(unique=True)),
                ('kind', models.CharField(choices=[('supplier_payment', 'Pago a proveedor'), ('expense', 'Gasto'), ('drop', 'Retiro parcial')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concept', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='store.goodsreceipt')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_outs', to='store.shift')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('kind', models.CharField(choices=[('receipt', 'Entrada'), ('sale', 'Venta'), ('adjustment', 'Ajuste'), ('return', 'Devolución')], max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='store.product')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='store.goodsreceipt')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.sale')),
                ('sale_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='store.salereturn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.DecimalField(decimal_places=3, max_digits=12)),
                ('counted', models.DecimalField(decimal_places=3, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('adjustment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.stockmovement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('register',), name='one_open_shift_per_register'),
        ),
    ]
