<#
.SYNOPSIS
  Installs Tienda POS on a Windows 10/11 computer (the store laptop).

.DESCRIPTION
  Creates the virtual environment, installs dependencies, writes .env with a new secret key and the
  LAN address, prepares the database, creates the owner account and (optionally) registers:
    - a scheduled task that starts the POS when the user logs in,
    - a daily verified backup,
    - a Windows Firewall rule so phones on the same Wi-Fi can connect,
    - a desktop shortcut that opens the POS as an app window.
  Run it again at any time: every step is idempotent.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts\windows\install.ps1
  powershell -ExecutionPolicy Bypass -File scripts\windows\install.ps1 -PrinterHost 192.168.1.50 -BackupDir E:\TiendaPOS-backups
  powershell -ExecutionPolicy Bypass -File scripts\windows\install.ps1 -PythonExe C:\Python313\python.exe
#>
param(
    [string]$PythonExe = '',
    [string]$PrinterHost = '',
    [int]$Port = 8008,
    [string]$BackupDir = '',
    [switch]$SkipAutostart,
    [switch]$SkipSuperuser,
    [switch]$SeedCatalog
)
$ErrorActionPreference = 'Stop'
$Root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
Set-Location $Root
function Step($text) { Write-Host "`n==> $text" -ForegroundColor Green }
# Run a native command and stop on a non-zero exit code (PowerShell 5 does not do it by itself).
function Invoke-Checked { & $args[0] @($args | Select-Object -Skip 1); if ($LASTEXITCODE) { throw "Command failed ($LASTEXITCODE): $($args -join ' ')" } }

Step 'Checking Python (3.12 or 3.13 required)'
$python = $null
$candidates = @('py -3.13', 'py -3.12', 'python')
if ($PythonExe) { $candidates = @("$PythonExe") }
foreach ($candidate in $candidates) {
    $exe, $arg = if ($PythonExe) { $PythonExe, $null } else { $candidate.Split(' ') }
    try {
        $version = & $exe @($arg | Where-Object { $_ }) -c 'import sys; print(*sys.version_info[:2], sep=chr(46))' 2>$null  # no inner double quotes: PowerShell 5 strips them
        if ($version -in @('3.12', '3.13')) { $python = $candidate; break }
    } catch { }
}
if (-not $python) {
    Write-Host 'Python 3.12 or 3.13 was not found. Install it with:' -ForegroundColor Yellow
    Write-Host '  winget install Python.Python.3.13' -ForegroundColor Yellow
    Write-Host 'or from https://www.python.org/downloads/ (check "Add python.exe to PATH"), then run this script again.'
    exit 1
}
Write-Host "Using: $python ($version)"

Step 'Creating the virtual environment and installing dependencies'
if (-not (Test-Path '.venv\Scripts\python.exe')) {
    $exe, $arg = if ($PythonExe) { $PythonExe, $null } else { $python.Split(' ') }
    & $exe @($arg | Where-Object { $_ }) -m venv .venv
}
$Py = Join-Path $Root '.venv\Scripts\python.exe'
Invoke-Checked $Py -m pip install --disable-pip-version-check --quiet --upgrade pip
Invoke-Checked $Py -m pip install --disable-pip-version-check --quiet -r requirements.txt

Step 'Writing .env (kept outside Git)'
$lanIp = (Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object { $_.IPAddress -notmatch '^(127\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.)' -and $_.PrefixOrigin -ne 'WellKnown' } |
    Sort-Object -Property InterfaceMetric | Select-Object -First 1).IPAddress
if (-not (Test-Path '.env')) {
    $secret = & $Py -c 'import secrets; print(secrets.token_urlsafe(50))'
    $hosts = @('127.0.0.1', 'localhost') + @($lanIp | Where-Object { $_ })
    $lines = @(
        '# Generated by scripts/windows/install.ps1. See .env.example for every option.',
        "POS_SECRET_KEY=$secret",
        'POS_DEBUG=0',
        "POS_ALLOWED_HOSTS=$($hosts -join ',')",
        "POS_PORT=$Port",
        "POS_PRINTER_HOST=$PrinterHost",
        'POS_PRINTER_PORT=9100',
        'POS_PRINTER_COLUMNS=42',
        'POS_PRINTER_ACCENTS=1'
    )
    if ($BackupDir) { $lines += "POS_BACKUP_DIR=$BackupDir" }
    Set-Content -Path '.env' -Value $lines -Encoding UTF8
    Write-Host "Created .env (LAN address: $lanIp)."
} else {
    Write-Host '.env already exists; it was not changed.'
}

Step 'Preparing the database and static files'
Invoke-Checked $Py manage.py migrate --noinput --verbosity 0
Invoke-Checked $Py manage.py collectstatic --noinput --verbosity 0
Invoke-Checked $Py manage.py check

if (-not $SkipSuperuser) {
    $hasOwner = & $Py manage.py shell -c 'from django.contrib.auth import get_user_model; print(get_user_model().objects.filter(is_superuser=True).exists())'
    if ($hasOwner -ne 'True') {
        Step 'Create the OWNER account (full access: catalog, receiving, reports, returns)'
        & $Py manage.py createsuperuser
    }
}
if ($SeedCatalog) {
    Step 'Loading the reference grocery catalog (approximate prices, no stock)'
    Invoke-Checked $Py manage.py seed_catalog
}

if (-not $SkipAutostart) {
    Step 'Registering automatic start at logon and the daily backup'
    $start = Join-Path $Root 'scripts\windows\start.ps1'
    $backup = Join-Path $Root 'scripts\windows\backup.ps1'
    $startAction = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$start`""
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)
    Register-ScheduledTask -TaskName 'TiendaPOS' -Action $startAction -Trigger (New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME) -Settings $settings -Description 'Starts the Tienda POS server' -Force | Out-Null
    $backupAction = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$backup`""
    Register-ScheduledTask -TaskName 'TiendaPOS-Backup' -Action $backupAction -Trigger (New-ScheduledTaskTrigger -Daily -At '22:00') -Settings (New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries) -Description 'Daily verified backup of the Tienda POS database' -Force | Out-Null
    Write-Host 'Scheduled tasks: TiendaPOS (at logon) and TiendaPOS-Backup (daily 22:00, or at next start if missed).'

    Step 'Allowing phones on the same Wi-Fi (private networks only)'
    $isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
    if ($isAdmin) {
        if (-not (Get-NetFirewallRule -DisplayName 'Tienda POS' -ErrorAction SilentlyContinue)) {
            New-NetFirewallRule -DisplayName 'Tienda POS' -Direction Inbound -Protocol TCP -LocalPort $Port -Profile Private -Action Allow | Out-Null
        }
        Write-Host "Firewall rule 'Tienda POS' allows TCP $Port on private networks."
    } else {
        Write-Host "Not running as administrator: to let phones connect, run once in an admin PowerShell:" -ForegroundColor Yellow
        Write-Host "  New-NetFirewallRule -DisplayName 'Tienda POS' -Direction Inbound -Protocol TCP -LocalPort $Port -Profile Private -Action Allow"
    }

    Step 'Creating the desktop shortcut'
    $edge = @("${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe", "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe") | Where-Object { Test-Path $_ } | Select-Object -First 1
    if ($edge) {
        $shell = New-Object -ComObject WScript.Shell
        $link = $shell.CreateShortcut((Join-Path ([Environment]::GetFolderPath('Desktop')) 'Tienda POS.lnk'))
        $link.TargetPath = $edge
        $link.Arguments = "--app=http://127.0.0.1:$Port/"
        $link.Description = 'Abrir la caja'
        $link.Save()
        Write-Host "Desktop shortcut 'Tienda POS' opens the POS in its own window."
    }
    Start-ScheduledTask -TaskName 'TiendaPOS'
}

Step 'Done'
Write-Host "Open http://127.0.0.1:$Port/ on this computer."
if ($lanIp) { Write-Host "Phones on the same Wi-Fi: http://${lanIp}:$Port/  (fix this IP in the router with a DHCP reservation)" }
if (-not $PrinterHost) { Write-Host 'No network printer configured: tickets print from the browser. See docs/printer.md to add the Epson.' }
